
    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table recipes.authority if exists;

    drop table recipes.category if exists;

    drop table recipes.comment if exists;

    drop table recipes.file_data if exists;

    drop table recipes.ingredient if exists;

    drop table recipes.recipe if exists;

    drop table recipes.recipe_image_data if exists;

    drop table recipes.recipe_ingredients_data if exists;

    drop table recipes.recipes_tags_map if exists;

    drop table recipes.tag if exists;

    drop table recipes.unit_of_measure if exists;

    drop table recipes.user if exists;

    drop table recipes.word if exists;

    create table recipes.authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table recipes.category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table recipes.comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table recipes.ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipes.recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipes.recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes.recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table recipes.tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table recipes.unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table recipes.user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table recipes.word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table recipes.authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references recipes.user;

    alter table recipes.comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references recipes.category;

    alter table recipes.recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references recipes.file_data;

    alter table recipes.recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipes.recipe;

    alter table recipes.recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references recipes.tag;

    alter table recipes.recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipes.recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;

    drop table authority if exists;

    drop table category if exists;

    drop table comment if exists;

    drop table file_data if exists;

    drop table ingredient if exists;

    drop table recipe if exists;

    drop table recipe_image_data if exists;

    drop table recipe_ingredients_data if exists;

    drop table recipes_tags_map if exists;

    drop table tag if exists;

    drop table unit_of_measure if exists;

    drop table user if exists;

    drop table word if exists;

    create table authority (
       authority varchar(255) not null,
        username varchar(255),
        primary key (authority)
    );

    create table category (
       id bigint generated by default as identity,
        description varchar(250) not null,
        primary key (id)
    );

    create table comment (
       id bigint generated by default as identity,
        inserted_dt timestamp,
        text clob,
        username varchar(255),
        recipe_fk bigint,
        primary key (id)
    );

    create table file_data (
       id bigint generated by default as identity,
        data blob,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table ingredient (
       id bigint generated by default as identity,
        amount decimal(19,2),
        unit_of_measure varchar(255),
        ingredient_name varchar(255),
        recipe_fk bigint,
        uom varchar(255),
        primary key (id)
    );

    create table recipe (
       id bigint generated by default as identity,
        cook_time integer,
        description varchar(255),
        directions clob,
        difficulty varchar(255),
        portions integer,
        prep_time integer,
        source varchar(255) not null,
        title varchar(250) not null,
        url varchar(255),
        category_fk bigint,
        primary key (id)
    );

    create table recipe_image_data (
       id bigint generated by default as identity,
        file_type varchar(255),
        recipe_image_data bigint,
        recipe_fk bigint,
        primary key (id)
    );

    create table recipe_ingredients_data (
       id bigint generated by default as identity,
        ing_ingredient_list binary(255),
        ing_measure_list binary(255),
        ing_quantity_list binary(255),
        primary key (id)
    );

    create table recipes_tags_map (
       recipe_fk bigint not null,
        tag_fk bigint not null,
        primary key (recipe_fk, tag_fk)
    );

    create table tag (
       id bigint generated by default as identity,
        value varchar(255),
        primary key (id)
    );

    create table unit_of_measure (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table user (
       username varchar(255) not null,
        enabled boolean not null,
        password varchar(255) not null,
        primary key (username)
    );

    create table word (
       id bigint generated by default as identity,
        word varchar(255),
        primary key (id)
    );

    alter table authority 
       add constraint FKljgmd4h8prtl0nk1r6dj4by1r 
       foreign key (username) 
       references user;

    alter table comment 
       add constraint FK9s2v59jhc0uid7x9k5m1k4ucc 
       foreign key (recipe_fk) 
       references recipe;

    alter table ingredient 
       add constraint FKkk0kuq04waku9mck92f0yee04 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipe 
       add constraint FKb4t2mdoirdarhgd9llv2jotc3 
       foreign key (category_fk) 
       references category;

    alter table recipe_image_data 
       add constraint FKqkuxhh0nfp1sw8n3ckolu8j98 
       foreign key (recipe_image_data) 
       references file_data;

    alter table recipe_image_data 
       add constraint FKo0ytahedcdtvo8cuiaypnkm1v 
       foreign key (recipe_fk) 
       references recipe;

    alter table recipes_tags_map 
       add constraint FK4ch55tucnpc5n9vapx40dcft9 
       foreign key (tag_fk) 
       references tag;

    alter table recipes_tags_map 
       add constraint FK5ss3dt4l282sya95ym0aqqedx 
       foreign key (recipe_fk) 
       references recipe;
