server:
  servlet:
    context-path: /guessme
  port: 8081
#  context-path: /guessme   deprecated

spring:
  datasource:
    url: jdbc:mysql://ec2-34-220-115-146.us-west-2.compute.amazonaws.com:3306/recipes
    username: nnuser
    password: e0af0e608cd5bd2fdfd64ce6efda35cce54fc266f15e09583b1c969b92184046
  liquibase:
    outputChangeLogFile: src/main/resources/liquibase-outputChangeLog.xml  
  jpa:
    hibernate:
      ddl-auto: none
# validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: np_database_create.sql

