server:
  servlet:
    context-path: /recipes
  port: 8081
#  context-path: /guessme   deprecated

spring:
  datasource:
    url: jdbc:postgresql://ec2-75-101-212-64.compute-1.amazonaws.com:5432/dd5mptuunin77f
    username: jdnsyxdidcbnil
    password: 37ac51914e3ca62858332459bb34b2543f9a0ae9adde9d53bdb765325e66a1bf

  jpa:
    hibernate:
      ddl-auto: none
# validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: np_database_create.sql

