asasfsafasfasf

CREATE SCHEMA IF NOT EXISTS asocijacijeAAA

create table asocijacije.WORDAAA ( 
	ID INTEGER NOT null,
	WORD varchar(100) NOT NULL,
	CATEGORY_FK INTEGER NOT null
)

ALTER TABLE asocijacije.WORDAAA ADD CONSTRAINT WORD_PK PRIMARY KEY (ID);
create unique index WORD_IX1AAA on asocijacije.WORD (WORD) ;

create table asocijacije.CATEGORYAAA ( 
	ID INTEGER NOT null,
	CAT_NAME varchar(100) NOT NULL,
	CAT_DESC varchar(100)
)

ALTER TABLE asocijacije.CATEGORYAAA ADD CONSTRAINT CATEGORY_PK PRIMARY KEY (ID);
create unique index CATEGORY_IX1AAA on asocijacije.CATEGORY (CAT_NAME) ;

ALTER TABLE asocijacije.WORDAAA ADD CONSTRAINT C_FK_WORD_CATEG FOREIGN KEY (CATEGORY_FK) REFERENCES asocijacije.CATEGORY(ID) ON DELETE RESTRICT;

